version: '3.8'

services: 
  redis-master:
    container_name: redis-master
    image: redis:6-alpine
    volumes:
      - "./.data:/data"
    ports:
      - "6379:6379"
    restart: always
    networks:
        redis: null
        grabslabs-backend_api: null
        nginx-network:
            aliases:
              - redis-master  
 
  redis-slave:
    image: redis:6-alpine
    command: redis-server --slaveof redis-master 6379
    links:
      - redis-master
    volumes:
      - "./.data:/data"
    restart: always
    networks:
        redis: null
        grabslabs-backend_api: null
        nginx-network:
            aliases:
              - redis-slave  
     
  redis-sentinel:
    build: 
      context: ./redis-sentinel
    links:
      - redis-master  
    restart: always    
    deploy:
      replicas: 3
    networks:        
        redis: null
        grabslabs-backend_api: null
        nginx-network:
            aliases:
              - redis-sentinel 

networks:
  redis:
    driver: bridge
  grabslabs-backend_api:
    external:
        name: grabslabs-backend_api
  nginx-network:
    external:
        name: nginx-network
