version: '3.8'

services: 
  redis-master:
    image: redis:6-alpine
    volumes:
      - "./.data:/data"
    ports:
      - "6379:6379"
    networks:
        redis-network: null
        grabslabs-backend_api: null
        nginx-network:
            aliases:
              - redis-master
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 3
      update_config:
        parallelism: 1
        delay: 10s
        monitor: 5s
        failure_action: rollback
        max_failure_ratio: 0.75
      restart_policy:
        condition: any
        delay: 3s
        max_attempts: 5
        window: 60s
 
  redis-slave:
    image: redis:6-alpine
    command: redis-server --slaveof redis-master 6379
    links:
      - redis-master
    volumes:
      - "./.data:/data"
    networks:
        redis-network: null
        grabslabs-backend_api: null
        nginx-network:
            aliases:
              - redis-slave
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 3
      update_config:
        parallelism: 1
        delay: 10s
        monitor: 5s
        failure_action: rollback
        max_failure_ratio: 0.75
      restart_policy:
        condition: any
        delay: 3s
        max_attempts: 5
        window: 60s
     
  redis-sentinel:
    image: '${DOCKER_REGISTRY-}redis-sentinel'
    links:
      - redis-master
    networks:        
        redis-network: null
        grabslabs-backend_api: null
        nginx-network:
            aliases:
              - redis-sentinel
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 3
      update_config:
        parallelism: 1
        delay: 10s
        monitor: 5s
        failure_action: rollback
        max_failure_ratio: 0.75
      restart_policy:
        condition: any
        delay: 3s
        max_attempts: 5
        window: 60s

networks:
  redis-network:
    name: redis-network
    external: true
  grabslabs-backend_api:
    name: grabslabs-backend_api
    external: true
  nginx-network:
    name: nginx-network
    external: true

